package domain.model

import currencyapp.composeapp.generated.resources.Res
import currencyapp.composeapp.generated.resources.compose_multiplatform
import org.jetbrains.compose.resources.DrawableResource

enum class CurrencyCode(
    val country: String
) {
    USD("United States"),
    CAD("Canada"),
    GBP("United Kingdom"),
    EUR("European Union"),
    JPY("Japan"),
    AUD("Australia"),
    INR("India"),
    CNY("China"),
    CHF("Switzerland"),
    RUB("Russia"),
    BRL("Brazil"),
    ZAR("South Africa"),
    MXN("Mexico"),
    NZD("New Zealand"),
    SEK("Sweden"),
    NOK("Norway"),
    SGD("Singapore"),
    HKD("Hong Kong"),
    KRW("South Korea"),
    TRY("Turkey"),
    PLN("Poland"),
    DKK("Denmark"),
    HUF("Hungary"),
    CZK("Czech Republic"),
    ILS("Israel"),
    MYR("Malaysia"),
    PHP("Philippines"),
    IDR("Indonesia"),
    THB("Thailand"),
    VND("Vietnam"),
    PKR("Pakistan"),
    BDT("Bangladesh"),
    LKR("Sri Lanka"),
    SAR("Saudi Arabia"),
    AED("United Arab Emirates"),
    QAR("Qatar"),
    KWD("Kuwait"),
    BHD("Bahrain"),
    OMR("Oman"),
    JOD("Jordan"),
    EGP("Egypt"),
    NGN("Nigeria"),
    KES("Kenya"),
    GHS("Ghana"),
    TZS("Tanzania"),
    UGX("Uganda"),
    RWF("Rwanda"),
    MAD("Morocco"),
    DZD("Algeria"),
    TND("Tunisia"),
    ARS("Argentina"),
    CLP("Chile"),
    COP("Colombia"),
    PEN("Peru"),
    UYU("Uruguay"),
    PYG("Paraguay"),
    BOB("Bolivia"),
    CUP("Cuba"),
    CRC("Costa Rica"),
    GTQ("Guatemala"),
    HNL("Honduras"),
    NIO("Nicaragua"),
    PAB("Panama"),
    DOP("Dominican Republic"),
    JMD("Jamaica"),
    TTD("Trinidad and Tobago"),
    BBD("Barbados"),
    BSD("Bahamas"),
    KYD("Cayman Islands"),
    BZD("Belize"),
    XCD("Eastern Caribbean"),
    FJD("Fiji"),
    PGK("Papua New Guinea"),
    WST("Samoa"),
    SBD("Solomon Islands"),
    TOP("Tonga"),
    VUV("Vanuatu"),
    KZT("Kazakhstan"),
    UZS("Uzbekistan"),
    AZN("Azerbaijan"),
    GEL("Georgia"),
    AMD("Armenia"),
    KGS("Kyrgyzstan"),
    TJS("Tajikistan"),
    BYN("Belarus"),
    UAH("Ukraine"),
    MDL("Moldova"),
    RSD("Serbia"),
    MKD("North Macedonia"),
    BGN("Bulgaria"),
    RON("Romania"),
    HRK("Croatia"),
    BAM("Bosnia and Herzegovina"),
    ALL("Albania"),
    ISK("Iceland"),
    LTL("Lithuania"),
    LVL("Latvia"),
    EEK("Estonia");
}
